# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan Klassen ₰
email: forivall@gmail.com
email_alt: jordan@klassen.me.uk
fullname: Jordan Klassen
longname: Jordan James Klassen
description: >
  Hi. I'm Jordan Klassen. My alias is forivall. I write code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://forivall.com" # the base hostname & protocol for your site
twitter_username: forivall
github_username:  forivall
stackoverflow_username:  490829/forivall
facebook_username:  jordanklassen
linkedin_username:  jordanklassen
spotify_username:  forivall
instagram_username:  forivall
bitbucket_username:  forivall

# Build settings
markdown: kramdown
gems:
  - jemoji
